### ISSUE TITLE
Build error with ble_amdtp_raspPi 

### ISSUE THREAD

**Issue by mraugit** [paulvha/apollo3#2]
I got the following error when I try to compile ble_amdtp_raspPi with bluez-5.50 or bluez-5.5:
```
compiling source files
  amdtc
amdtc.c: In function ‘parseNotification’:
amdtc.c:171:27: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?
     if (handle == amdtpCb.ACK_handle)
                           ^~~~~~~~~~
                           TX_handle
amdtc.c: In function ‘events_handler’:
amdtc.c:234:39: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?
                 if (handle == amdtpCb.RX_handle ) g_print("(data)\n");
                                       ^~~~~~~~~
                                       TX_handle
amdtc.c: In function ‘enable_comms’:
amdtc.c:447:22: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?
     handle = amdtpCb.RX_handle + 1;
                      ^~~~~~~~~
                      TX_handle
amdtc.c:452:22: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?
     handle = amdtpCb.ACK_handle + 1;
                      ^~~~~~~~~~
                      TX_handle
amdtc.c: In function ‘read_characteristics’:
amdtc.c:493:21: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?
             amdtpCb.RX_handle = range->value_handle;
                     ^~~~~~~~~
                     TX_handle
amdtc.c:498:21: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?
             amdtpCb.ACK_handle = range->value_handle;
                     ^~~~~~~~~~
                     TX_handle
```

Raspberry Pi 3 with:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by paulvha** [comment]
Solved the issue and will post new release soon. One more other warning to crack...

________________________________
Van: mraugit <notifications@github.com>
Verzonden: vrijdag 13 november 2020 10:51
Aan: paulvha/apollo3 <apollo3@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [paulvha/apollo3] Build error with ble_amdtp_raspPi (#2)


I got the following error when I try to compile ble_amdtp_raspPi with bluez-5.50 or bluez-5.5:

compiling source files

  amdtc

amdtc.c: In function ‘parseNotification’:

amdtc.c:171:27: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?

     if (handle == amdtpCb.ACK_handle)

                           ^~~~~~~~~~

                           TX_handle

amdtc.c: In function ‘events_handler’:

amdtc.c:234:39: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?

                 if (handle == amdtpCb.RX_handle ) g_print("(data)\n");

                                       ^~~~~~~~~

                                       TX_handle

amdtc.c: In function ‘enable_comms’:

amdtc.c:447:22: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?

     handle = amdtpCb.RX_handle + 1;

                      ^~~~~~~~~

                      TX_handle

amdtc.c:452:22: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?

     handle = amdtpCb.ACK_handle + 1;

                      ^~~~~~~~~~

                      TX_handle

amdtc.c: In function ‘read_characteristics’:

amdtc.c:493:21: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘RX_handle’; did you mean ‘TX_handle’?

             amdtpCb.RX_handle = range->value_handle;

                     ^~~~~~~~~

                     TX_handle

amdtc.c:498:21: error: ‘amdtpCb_t’ {aka ‘struct <anonymous>’} has no member named ‘ACK_handle’; did you mean ‘TX_handle’?

             amdtpCb.ACK_handle = range->value_handle;

                     ^~~~~~~~~~

                     TX_handle

**Comment by paulvha** [comment]
updated version is now posted. tested with Bluez5.55
