### ISSUE TITLE
Could not match all handles . Service handle mismatch !!

### ISSUE THREAD

**Issue by mraugit** [paulvha/apollo3#3]
I try to communicate between sparkfun edge as amdtp_server and RaspPi 3 as client. The application teminates unexpected in funktion read_characteristics. Code is unchanged except the activation of logging.

Arduino log:
```
19:49:42.062 -> Starting Bluetooth
19:49:44.163 -> 
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_466064\sketch\amdtp_common.c, line: 97
19:49:44.217 -> 
Bluetooth device active, waiting for connections...
19:49:44.217 -> local address 56:77:88:23:ab:ef
19:49:44.217 -> local name Artemis AMDTP BLE
19:49:47.067 -> 
Connected event, central: b8:27:eb:7:f5:19
19:49:49.723 -> 
Disconnected event, central: b8:27:eb:7:f5:19
19:49:49.723 -> 
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_466064\sketch\amdtp_common.c, line: `97
```

RasPi log:
```
./amdtc -b 56:77:88:23:ab:ef -I -v 2
Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service start handle = 0x000a, end handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Could not match all handles
. Service handle mismatch !!
````

**Comment by paulvha** [comment]
weird
 I will give it another try tomorrow (evening here)..

regards,
Paul

________________________________
Van: mraugit <notifications@github.com>
Verzonden: vrijdag 13 november 2020 19:59
Aan: paulvha/apollo3 <apollo3@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [paulvha/apollo3] Could not match all handles . Service handle mismatch !! (#3)


I try to communicate between sparkfun edge as amdtp_server and RaspPi 3 as client. The application teminates unexpected in funktion read_characteristics. Code is unchanged except the activation of logging.

Arduino log:

19:49:42.062 -> Starting Bluetooth
19:49:44.163 ->
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_466064\sketch\amdtp_common.c, line: 97
19:49:44.217 ->
Bluetooth device active, waiting for connections...
19:49:44.217 -> local address 56:77:88:23:ab:ef
19:49:44.217 -> local name Artemis AMDTP BLE
19:49:47.067 ->
Connected event, central: b8:27:eb:7:f5:19
19:49:49.723 ->
Disconnected event, central: b8:27:eb:7:f5:19
19:49:49.723 ->
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_466064\sketch\amdtp_common.c, line: `97


RasPi log:

./amdtc -b 56:77:88:23:ab:ef -I -v 2
Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service start handle = 0x000a, end handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Could not match all handles
. Service handle mismatch !!

**Comment by paulvha** [comment]
somehow sources could mixed. The issue is fixe BUT... seems my Artemis ATP board is having issues (often failing to connect and hang on with lclient running on Ubuntu adn Rasperry PI as well as nRF connect.. Still working on it, but i have posted the updated Raspberry code. Maybe you can try as well.

**Comment by mraugit** [comment]
Now I get a segmentation fault in AmdtpSendPacketHandler (see logs)

Arduino log:
````
15:22:49.075 -> Starting Bluetooth
15:22:51.176 -> 
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 97
15:22:51.223 -> 
Bluetooth device active, waiting for connections...
15:22:51.223 -> local address 56:77:88:23:ab:ef
15:22:51.223 -> local name Artemis AMDTP BLE
15:23:03.834 -> 
Connected event, central: b8:27:eb:7:f5:19
15:23:04.939 -> 
15:23:04.939 -> RX receive 
15:23:04.939 -> Raw received (length 11) :  0x5 0x7E 0x20 0x7E 0x20 0x10 0x3 0x37 0xBE 0xB 0x4B
15:23:04.993 -> After encode (size 9) : 0x5 0x0 0x0 0x10 0x3 0x37 0xBE 0xB 0x4B
15:23:04.993 -> 
fm: AmdtpReceivePkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 150
15:23:04.993 -> 
pkt len = 0x5, pkt header = 0x1000 :
15:23:04.993 -> 
type = 1 : DATA sn = 0, enc = 0, ackEnabled = 0
15:23:04.993 -> 
fm: AmdtpPacketHandler, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 274
15:23:05.039 -> 
fm: AmdtpSendReply, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 474
15:23:05.039 -> 
fm: amdtpsSendAck, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 499
15:23:05.093 -> 
fm: AmdtpBuildPkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 373
15:23:05.093 -> 
15:23:05.093 -> ============== Ack Prepared for sending ========================
15:23:05.093 -> 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2 
15:23:05.093 -> 
15:23:05.093 -> ============== Decoded ========================
15:23:05.139 -> 
15:23:05.139 -> length 12
15:23:05.139 -> 0x5 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x2 0xD2 
15:23:05.139 -> 
15:23:05.139 -> 
15:23:05.139 -> Ack write: 0x5 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x2 0xD2
15:23:05.139 -> 
Received command with length 1 : 0x3 
15:23:05.139 -> 
Received HELLO / wakeup from client
15:23:05.139 -> 
fm: AmdtpSendData, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 517
15:23:05.193 -> 
fm: AmdtpsSendPacket, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 547
15:23:05.193 -> 
fm: AmdtpBuildPkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 373
15:23:05.239 -> 
15:23:05.239 -> ============== Data Prepared for sending ========================
15:23:05.239 -> 0x6 0x0 0x0 0x10 0x3 0x0 0x3C 0x41 0xF4 0x6A 
15:23:05.239 -> 
15:23:05.239 -> ============== Decoded ========================
15:23:05.239 -> 
15:23:05.239 -> length 13
15:23:05.239 -> 0x6 0x7E 0x20 0x7E 0x20 0x10 0x3 0x7E 0x20 0x3C 0x41 0xF4 0x6A 
15:23:05.239 -> 
15:23:05.239 -> 
fm: AmdtpSendPacketHandler, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 599
15:23:05.293 -> 
15:23:05.293 -> TX / data packet write:  0x6 0x7E 0x20 0x7E 0x20 0x10 0x3 0x7E 0x20 0x3C 0x41 0xF4 0x6A
15:23:07.294 -> 
Disconnected event, central: b8:27:eb:7:f5:19
15:23:07.294 -> 
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 97
````

RasPi log:
````
./amdtc -b 56:77:88:23:ab:ef -I -v 2
Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service
        start handle = 0x000a
        end handle = 0x0012
        uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Value handle = 0x000c, uuid = 00002760-08c2-11e1-9073-0e8ac72e0011, count = 1 of 3
Value handle = 0x000e, uuid = 00002760-08c2-11e1-9073-0e8ac72e0012, count = 2 of 3
Value handle = 0x0011, uuid = 00002760-08c2-11e1-9073-0e8ac72e0013, count = 3 of 3
enable_comms
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
 ===== sending  =====
0x5 0x7e 0x20 0x7e 0x20 0x10 0x3 0x37 0xbe 0xb 0x4b
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
Segmentation fault
````

**Comment by paulvha** [comment]
Can you check the enable_comms_cb() ?
I had that once and added a 'static boolean once' to prevent sent 2 times a sending an 'hallo' write_request. Seems that compiler on Buster or Bluz5.55 is having an issue with that. I am now checking 5.52 but it is not getting beyond getting primary services... I am afraid my Artemis board is having an issue.

________________________________
Van: mraugit <notifications@github.com>
Verzonden: zaterdag 14 november 2020 15:30
Aan: paulvha/apollo3 <apollo3@noreply.github.com>
CC: paulvha <paulvha@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [paulvha/apollo3] Could not match all handles . Service handle mismatch !! (#3)


Now I get a sementation fault in AmdtpSendPacketHandler (see logs)

Arduino log:

15:22:49.075 -> Starting Bluetooth
15:22:51.176 ->
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 97
15:22:51.223 ->
Bluetooth device active, waiting for connections...
15:22:51.223 -> local address 56:77:88:23:ab:ef
15:22:51.223 -> local name Artemis AMDTP BLE
15:23:03.834 ->
Connected event, central: b8:27:eb:7:f5:19
15:23:04.939 ->
15:23:04.939 -> RX receive
15:23:04.939 -> Raw received (length 11) :  0x5 0x7E 0x20 0x7E 0x20 0x10 0x3 0x37 0xBE 0xB 0x4B
15:23:04.993 -> After encode (size 9) : 0x5 0x0 0x0 0x10 0x3 0x37 0xBE 0xB 0x4B
15:23:04.993 ->
fm: AmdtpReceivePkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 150
15:23:04.993 ->
pkt len = 0x5, pkt header = 0x1000 :
15:23:04.993 ->
type = 1 : DATA sn = 0, enc = 0, ackEnabled = 0
15:23:04.993 ->
fm: AmdtpPacketHandler, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 274
15:23:05.039 ->
fm: AmdtpSendReply, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 474
15:23:05.039 ->
fm: amdtpsSendAck, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 499
15:23:05.093 ->
fm: AmdtpBuildPkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 373
15:23:05.093 ->
15:23:05.093 -> ============== Ack Prepared for sending ========================
15:23:05.093 -> 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2
15:23:05.093 ->
15:23:05.093 -> ============== Decoded ========================
15:23:05.139 ->
15:23:05.139 -> length 12
15:23:05.139 -> 0x5 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x2 0xD2
15:23:05.139 ->
15:23:05.139 ->
15:23:05.139 -> Ack write: 0x5 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x2 0xD2
15:23:05.139 ->
Received command with length 1 : 0x3
15:23:05.139 ->
Received HELLO / wakeup from client
15:23:05.139 ->
fm: AmdtpSendData, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 517
15:23:05.193 ->
fm: AmdtpsSendPacket, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 547
15:23:05.193 ->
fm: AmdtpBuildPkt, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 373
15:23:05.239 ->
15:23:05.239 -> ============== Data Prepared for sending ========================
15:23:05.239 -> 0x6 0x0 0x0 0x10 0x3 0x0 0x3C 0x41 0xF4 0x6A
15:23:05.239 ->
15:23:05.239 -> ============== Decoded ========================
15:23:05.239 ->
15:23:05.239 -> length 13
15:23:05.239 -> 0x6 0x7E 0x20 0x7E 0x20 0x10 0x3 0x7E 0x20 0x3C 0x41 0xF4 0x6A
15:23:05.239 ->
15:23:05.239 ->
fm: AmdtpSendPacketHandler, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 599
15:23:05.293 ->
15:23:05.293 -> TX / data packet write:  0x6 0x7E 0x20 0x7E 0x20 0x10 0x3 0x7E 0x20 0x3C 0x41 0xF4 0x6A
15:23:07.294 ->
Disconnected event, central: b8:27:eb:7:f5:19
15:23:07.294 ->
fm: amdtps_init, file: C:\Users\admin\AppData\Local\Temp\arduino_build_613340\sketch\amdtp_common.c, line: 97


RasPi log:

./amdtc -b 56:77:88:23:ab:ef -I -v 2
Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service
        start handle = 0x000a
        end handle = 0x0012
        uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Value handle = 0x000c, uuid = 00002760-08c2-11e1-9073-0e8ac72e0011, count = 1 of 3
Value handle = 0x000e, uuid = 00002760-08c2-11e1-9073-0e8ac72e0012, count = 2 of 3
Value handle = 0x0011, uuid = 00002760-08c2-11e1-9073-0e8ac72e0013, count = 3 of 3
enable_comms
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
 ===== sending  =====
0x5 0x7e 0x20 0x7e 0x20 0x10 0x3 0x37 0xbe 0xb 0x4b
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
Segmentation fault

**Comment by mraugit** [comment]
I've checked that. In the meantime I've updated Bluez to 5.55. The last logs have been created with 5.55.

characteristics_write_req returns not 0. So once is not set. Nevertheless, once should be declarated global to have an effect, right?

**Comment by paulvha** [comment]
hi

I have reconnected Pi3 with the Jessie release, uploaded Bluez 5.52, uploaded the new amdtc. Compiled, now some errors because of C99 declarations, but an easy fix. Works like a charm.. no issues.. maybe timeout issue  due to the Pi4 speed in Bluez ?? dont know yet..Clearly an issue with the PI4 / Buster / Bluez.

The boolean was declared static in the function. So only known in the function itself, but preserves it's value set during a previous call of the function. Should work..

regards,
Paul
________________________________
Van: mraugit <notifications@github.com>
Verzonden: zaterdag 14 november 2020 16:09
Aan: paulvha/apollo3 <apollo3@noreply.github.com>
CC: paulvha <paulvha@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [paulvha/apollo3] Could not match all handles . Service handle mismatch !! (#3)


I've checked that. In the meantime I've updated Bluez to 5.55. The last logs have been created with 5.55.

characteristics_write_req returns 0. So once is not set. Nevertheless, once should be declarated global to have an effect, right?

**Comment by mraugit** [comment]
Now it works also on my configuration with PI3 / Buster / Bluez Version 5.50. Made the following steps:

1. sudo apt --autoremove purge bluez
2. Removed other Bluez versions with "sudo make uninstall"  
3. sudo reboot
4. sudo apt-get update
5. sudo apt-get upgrade
6. sudo apt-get install pi-bluetooth (get repo version 5.50)
7. download Bluez 5.50 sources, and latest amdtc sources and build
````
Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service
        start handle = 0x000a
        end handle = 0x0012
        uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Value handle = 0x000c, uuid = 00002760-08c2-11e1-9073-0e8ac72e0011, count = 1 of 3
Value handle = 0x000e, uuid = 00002760-08c2-11e1-9073-0e8ac72e0012, count = 2 of 3
Value handle = 0x0011, uuid = 00002760-08c2-11e1-9073-0e8ac72e0013, count = 3 of 3
enable_comms
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
 ===== sending  =====
0x5 0x7e 0x20 0x7e 0x20 0x10 0x3 0x37 0xbe 0xb 0x4b
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
events_handler
Notification handle = 0x0011 (Acknowledge)
parseNotification
Data received : 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2
pkt len = 0x5
pkt header = 0x2000 : type = 2, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x00 0x8D 0xEF 0x02 0xD2
complete packet received
AMDTP_PKT_TYPE_ACK
events_handler
Notification handle = 0x000e (data)
parseNotification
Data received : 0x6 0x0 0x0 0x10 0x3 0x0 0x3C 0x41 0xF4 0x6A
pkt len = 0x6
pkt header = 0x1000 : type = 1, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x03 0x00 0x3C 0x41 0xF4 0x6A
complete packet received
AmdtpSendReply
amdtpcSendAck
============== Prepared for sending ========================
0x05 0x00 0x00 0x20 0x00 0x8D 0xEF 0x02 0xD2
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x02 0xD2
char_write_req_cb
Request was written successfully. Waiting for respond notification
events_handler
Notification handle = 0x0011 (Acknowledge)
parseNotification
Data received : 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2
pkt len = 0x5
pkt header = 0x2000 : type = 2, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x00 0x8D 0xEF 0x02 0xD2
complete packet received
AMDTP_PKT_TYPE_ACK
commACK_cb
UI 2 bytes data received : 0x3 0x0

Received HELLO responds

Make your selection :
0       Quit
1       Start receiving test data
2       Stop receiving test data
3       Read internal temperature in Celsius
4       Read internal temperature in Fahrenheit
5       Battery level in percentage
6       Battery level in percentage with load resistor
7       Turn LED on
8       Turn LED off
9       Read BME280 (if connected)
10      Read ADC channel
11      Read a digital pin
12      Set a pin HIGH
13      Set a pin LOW
14      Perform simple chat
30      Request server version number

Provide your choice :
````

**Comment by paulvha** [comment]
COOOOOL..

Thanks for sharing !!!

I am looking in (deep) details of the traces of BOTH Client and Server. Somehow, somewhere the Bluez stack is NOT sending the ACK where it should do. More and more I get the belief this is a timing issue and somewhere a delay or check of completion a previous send has to be included in the client. As result, the server is getting in an unresponsive state and hence the nRF Connect can also not reach the server anymore. I'll try to find out..

regards,
Paul

________________________________
Van: mraugit <notifications@github.com>
Verzonden: zaterdag 14 november 2020 18:33
Aan: paulvha/apollo3 <apollo3@noreply.github.com>
CC: paulvha <paulvha@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [paulvha/apollo3] Could not match all handles . Service handle mismatch !! (#3)


Now it works also on my configuration with PI3 / Buster / Bluez Version 5.50. Made the following steps:

  1.  sudo apt --autoremove purge bluez
  2.  Removed other Bluez versions with "sudo make uninstall"
  3.  sudo reboot
  4.  sudo apt-get update
  5.  sudo apt-get upgrade
  6.  sudo apt-get install pi-bluetooth (get repo version 5.50)
  7.  download Bluez 5.50 sources, and latest amdtc sources and build

Trying to Connect
Starting mainloop (waiting on connect)
connect_cb
Connected
read_all_primary
listen_start
extract_all_primary
attr handle = 0x0001, end grp handle = 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle = 0x0006, end grp handle = 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle = 0x000a, end grp handle = 0x0012 uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_handles
FOUND AMDTP service
        start handle = 0x000a
        end handle = 0x0012
        uuid: 00002760-08c2-11e1-9073-0e8ac72e1011
read_characteristics
Value handle = 0x000c, uuid = 00002760-08c2-11e1-9073-0e8ac72e0011, count = 1 of 3
Value handle = 0x000e, uuid = 00002760-08c2-11e1-9073-0e8ac72e0012, count = 2 of 3
Value handle = 0x0011, uuid = 00002760-08c2-11e1-9073-0e8ac72e0013, count = 3 of 3
enable_comms
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
 ===== sending  =====
0x5 0x7e 0x20 0x7e 0x20 0x10 0x3 0x37 0xbe 0xb 0x4b
enable_comms_cb
characteristics_write_req
============== Prepared for sending ========================
0x05 0x00 0x00 0x10 0x03 0x37 0xBE 0x0B 0x4B
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x10 0x03 0x37 0xBE 0x0B 0x4B
AmdtpSendPacketHandler
events_handler
Notification handle = 0x0011 (Acknowledge)
parseNotification
Data received : 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2
pkt len = 0x5
pkt header = 0x2000 : type = 2, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x00 0x8D 0xEF 0x02 0xD2
complete packet received
AMDTP_PKT_TYPE_ACK
events_handler
Notification handle = 0x000e (data)
parseNotification
Data received : 0x6 0x0 0x0 0x10 0x3 0x0 0x3C 0x41 0xF4 0x6A
pkt len = 0x6
pkt header = 0x1000 : type = 1, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x03 0x00 0x3C 0x41 0xF4 0x6A
complete packet received
AmdtpSendReply
amdtpcSendAck
============== Prepared for sending ========================
0x05 0x00 0x00 0x20 0x00 0x8D 0xEF 0x02 0xD2
============== Decoded sending ========================
0x05 0x7E 0x20 0x7E 0x20 0x20 0x7E 0x20 0x8D 0xEF 0x02 0xD2
char_write_req_cb
Request was written successfully. Waiting for respond notification
events_handler
Notification handle = 0x0011 (Acknowledge)
parseNotification
Data received : 0x5 0x0 0x0 0x20 0x0 0x8D 0xEF 0x2 0xD2
pkt len = 0x5
pkt header = 0x2000 : type = 2, sn = 0, enc = 0, ackEnabled = 0
============== Total Packet received ========================
0x00 0x8D 0xEF 0x02 0xD2
complete packet received
AMDTP_PKT_TYPE_ACK
commACK_cb
UI 2 bytes data received : 0x3 0x0

Received HELLO responds

Make your selection :
0       Quit
1       Start receiving test data
2       Stop receiving test data
3       Read internal temperature in Celsius
4       Read internal temperature in Fahrenheit
5       Battery level in percentage
6       Battery level in percentage with load resistor
7       Turn LED on
8       Turn LED off
9       Read BME280 (if connected)
10      Read ADC channel
11      Read a digital pin
12      Set a pin HIGH
13      Set a pin LOW
14      Perform simple chat
30      Request server version number

Provide your choice :

**Comment by paulvha** [comment]
I have spend a lot of time analyzing 
**Segmentation fault on Bluez 5.55**: turned out that the notify callback now has ONE extra parameter than on 5.52. I have made an update in gattrib.c to handle that and now it works without segmentation errors

**Freezing of amdtc client:** After long searching I know the root cause now. I have an extensive documentation it but in short: It is a response packet that is sent to the HCI layer on Apollo3, BUT not always received by the Bluez stack.  I have ordered a Bluetooth sniffer to understand whether the Apollo3 HCI layer has really transmitted it OR whether it gets lost by the Bluez-stack. It looks like it is Bluez(as it works on a slower system, but I want to be sure. 
Once I know I will update the documentation and the gattrib.c code to enable this to work on Bluez 5.55

**Comment by paulvha** [comment]
New code has been loaded. A number of timing issues on the Apollo3 Bluetooth chip was causing instability. Left and right changed the code to deal with that. Much more stable. The Arduino Client has now also been tested for Arduino Nano 33 BLE sense.
